# Data sources

Three datasets used in this project are pandemic statistics for US nursing homes -COVID-19 Nursing Home Data’, pandemic statistics across the US - ‘Medicare COVID-19 Cases & Hospitalizations’ and US nursing home ratings - ‘Provider Information’. We obtain these three datasets from The Centers for Medicare & Medicaid Services (CMS), a federal agency within the United States Department of Health and Human Services.

‘COVID-19 Nursing Home Data’ contains tracking information for over 15 thousand nursing homes under COVID-19 with more than 40 time points from May 24, 2020 to Nov 12, 2021. It is a detailed investigation on nursing homes with over 200 features that reveals statistics from perspectives of COVID-19 cases, laboratory tests, staff and personnel, and pandemic prevention resources etc. They mainly consist of string variables including nursing home providers’ names and states, numerical variables such as bed occupations, vaccination rates and COVID-19 confirmation rates, and binary variables such as sufficiency of resources and nursing staff. We do exploratory analysis for all possible factors on COVID-19 confirmation rates in this dataset and include our most informative results in the following parts.

One issue with this dataset is that missing entries take up more than half of the original dataset. After a closer analysis, as this dataset is constantly collected through a large-scale tracking survey, we discover that a large proportion of missing entries could be caused by sections of data that arrive on different dates during the survey. Therefore, by carefully selecting or aggregating data with close dates, we decreased the missing percentage significantly and successfully extracted high-quality datasets for analysis.

‘Medicare COVID-19 Cases & Hospitalizations’ is a dataset contains nationwide COVID-19 confirmation statistics with state specific data. We join the state average confirmation rates to the above dataset to reproduce a comparison from previous research on COVID-19 situations in nursing homes. We successfully verify our datasets and processing procedure by getting consistent results from this experiment.

‘Provider Information’ records the results for three cycles of examinations for 15 thousand nursing homes across the US from health inspections, caring levels, facility conditions, penalties, etc. These results are reflected by the Five-Star Quality Rating System implemented in October 2019 (CMS, 2021). We make use of the final result of this rating system, including quality measure ratings, staffing ratings, health inspection ratings and overall ratings, which are ordinal variables from 1 to 5.

