# Interactive component





<!-- Load d3.js -->
<script src="https://d3js.org/d3.v4.js"></script>
<script src="https://d3js.org/d3-scale-chromatic.v1.min.js"></script>
<div>
  <l1>*Users could use the button of the first graph to check the time series of different nursing house COVID-19 data.</l1>
</div>
<!-- Initialize a select button -->
<select id="selectButton"></select>

<!-- Create a div where the graph will take place -->
<div id="my_dataviz"></div>

<!-- Color Scale -->
<script>

    // set the dimensions and margins of the graph
    var margin = {top: 10, right: 100, bottom: 30, left: 60},
        width = 500
        height = 350
    
    // append the svg object to the body of the page
    var svg = d3.select("#my_dataviz")
      .append("svg")
        .attr("width", width + margin.left + margin.right)
        .attr("height", height + margin.top + margin.bottom)
      .append("g")
        .attr("transform",
              "translate(" + margin.left + "," + margin.top + ")");
    
    //Read the data
    d3.csv("https://raw.githubusercontent.com/ScottSu0114/vizhub/main/test1.csv",
    
        function(d){
            return { time : d3.timeParse("%Y-%m-%d")(d.time),
            ResidentConfirmedCases : d.ResidentConfirmedCases, 
            ResidentDeathCases : d.ResidentDeathCases,
            ResidentWeeklyIncreaseCases : d.ResidentWeeklyIncreaseCases,
            StaffConfirmedCases : d.StaffConfirmedCases }
        },

        function(data) {
        console.log(data)
        // List of groups (here I have one group per column)
        var allGroup = ["ResidentConfirmedCases", "ResidentDeathCases", "ResidentWeeklyIncreaseCases", "StaffConfirmedCases"]
        //var allGroup = ["Resident Confirmed Cases", "Resident Death Cases","Resident Weekly Increase Cases", "Staff Confirmed Cases"]
        
        // add the options to the button
        d3.select("#selectButton")
          .selectAll('myOptions')
             .data(allGroup)
          .enter()
            .append('option')
          .text(function (d) { return d; }) // text showed in the menu
          .attr("value", function (d) { return d; }) // corresponding value returned by the button
    
        // A color scale: one color for each group
        var myColor = d3.scaleOrdinal()
          .domain(allGroup)
          .range(d3.schemeSet2);
    
        // Add X axis --> it is a date format
        var x = d3.scaleTime()
          .domain(d3.extent(data, function(d) { return d.time; }))
          .range([ 0, width ]);
        svg.append("g")
          .attr("transform", "translate(0," + height + ")")
          .call(d3.axisBottom(x));
    
        // Add Y axis
        var y = d3.scaleLinear()
          .domain( [0,1000000])
          .range([ height, 0 ]);
        svg.append("g")
          .call(d3.axisLeft(y));
    
        // Initialize line with group a
        var line = svg
          .append('g')
          .append("path")
            .datum(data)
            .attr("d", d3.line()
              .x(function(d) { return x(+d.time) })
              .y(function(d) { return y(+d.ResidentConfirmedCases) })
            )
            .attr("stroke", function(d){ return myColor("admissions") })
            .style("stroke-width", 4)
            .style("fill", "none")
    
        // A function that update the chart
        function update(selectedGroup) {
    
          // Create new data with the selection?
          var dataFilter = data.map(function(d){return {time: d.time, value:d[selectedGroup]} })
          console.log(dataFilter.value);
          // Give these new data to update line
          line
              .datum(dataFilter)
              .transition()
              .duration(1000)
              .attr("d", d3.line()
                .x(function(d) { return x(+d.time) })
                .y(function(d) { return y(+d.value) })
              )
              .attr("stroke", function(d){ return myColor(selectedGroup) })
        }
    
        // When the button is changed, run the updateChart function
        d3.select("#selectButton").on("change", function(d) {
            // recover the option that has been chosen
            var selectedOption = d3.select(this).property("value")
            // run the updateChart function with this selected option
            update(selectedOption)
        })
    
    })   
</script>
