# Interactive Component & Conclusion
<script src="https://d3js.org/d3.v4.js"></script>
<script src="https://d3js.org/d3-scale-chromatic.v1.min.js"></script>
<script src="https://github.com/PMSI-AlignAlytics/dimple/releases/download/2.3.0/dimple.v2.3.0.min.js"></script>
<l1>*From the second graph, users are able to observe the trend of full vaccination rates of residents and staffs of nursing houses. It also shows the occupancy (how many percentage of beds has been occupied by residents). Users can hover on the line to check the specific rate at each date. </l1>

<div id="chartContainer"></div>
<script>
      var svg = dimple.newSvg("#chartContainer", 600, 500);
      d3.csv("https://raw.githubusercontent.com/RubyRong/Covid19Health/main/covid-inter.csv", function(error, data) {
          if(error){ 
              console.log(error); 
          } 
          var myChart = new dimple.chart(svg, data);
          myChart.setBounds(60, 60, 505, 305);
          var x = myChart.addCategoryAxis("x", "Date")
          myChart.addMeasureAxis("y", "Rate(%)");
          var lines = myChart.addSeries("Name", dimple.plot.line);
          myChart.addLegend(60, 10, 500, 20, "right");
          lines.lineWeight = 1;
          myChart.draw();
      }); 
</script>
<l2>*The combination of two graphs can help users understand the relationship between each factor and COVID-19 cases of nursing houses.One of the most significant takeaway from these interactive plots is that as the vaccination rate increases from the mid of 2021, the rapid growing trend starting from late 2020 has been slowed down.</l2>
<div id="chartContainer"></div>


In summary, our research suggests a close relation between high vaccination rates and low COVID-19 confirmation rates, a counter-intuitive negative relationship between bed occupation rates and COVID-19 confirmation rates and weak impacts of sufficiency of resources and nursing staff at the current stage. We also provide further evidence or explanations to phenomena above.

To expand this research, in addition to research on the elderly in nursing homes, attentions can be payed on children in kindergartens and schools, because children can be less aware of infectious diseases than adults and have weaker resistance to diseases. According to the current situation, covid will not stop soon. As time progresses, new factors may arise. We should also keep learning and exploring to discover more new information to help reduce the rate of covid infection. 

From the perspective data science experience, we have learned that data is helpful for providing insights and evidence, but it is important to reflect on reality or resort to scientific experiments before coming to conclusions. 


References

1. Williams, CS, Zheng, Q, White, AJ, et al. The association of nursing home quality ratings and spread of COVID-19. J Am Geriatr Soc. 2021; 69( 8): 2070– 2078. https://doi.org/10.1111/jgs.17309

2. State COVID-19 Data and Policy Actions, KFF, accessed Dec 8, 2021, https://www.kff.org/coronavirus-covid-19/issue-brief/state-covid-19-data-and-policy-actions/

3. COVID-19 Nursing Home Data, The Centers for Medicare & Medicaid Services, accessed Dec 5, 2021, https://data.cms.gov/covid-19/covid-19-nursing-home-data

4. Five-Star Quality Rating System, The Centers for Medicare & Medicaid Services, accessed Dec 5, 2021, https://www.cms.gov/Medicare/Provider-Enrollment-and-Certification/CertificationandComplianc/FSQRS

5. Medicare COVID-19 Cases & Hospitalizations, The Centers for Medicare & Medicaid Services, accessed Dec 5, 2021, https://data.cms.gov/covid-19/medicare-covid-19-cases-hospitalizations

6. Provider Information, The Centers for Medicare & Medicaid Services, accessed Dec 5, 2021, https://data.cms.gov/provider-data/dataset/4pq5-n9py
